drop table if exists subcable CASCADE;

create table subcable
(
    id bigint generated by default as identity,
    subCableName varchar(255),
    primary key(id)
);

insert into subcable(subCableName) values('spring2')